title: COVID-19 - Workflow2
resource: ornl.summit
queue: batch
schema_: local
project: MED110
walltime_min: 360
max_iteration: 4
cpus_per_node: 42
gpus_per_node: 6
hardware_threads_per_cpu: 4
experiment_directory: /path/to/experiment
md_stage:
    pre_exec:
    - . /sw/summit/python/3.6/anaconda3/5.3.0/etc/profile.d/conda.sh
    - module load cuda/9.1.85
    - conda activate /gpfs/alpine/proj-shared/med110/conda/openmm
    - export PYTHONPATH=/path/to/run_openmm/directory:$PYTHONPATH
    executable:
    - /gpfs/alpine/proj-shared/med110/conda/openmm/bin/python
    arguments:
    - /path/to/run_openmm/run_openmm.py
    cpu_reqs:
        processes: 1
        process_type: 'null'
        threads_per_process: 4
        thread_type: OpenMP
    gpu_reqs:
        processes: 1
        process_type: 'null'
        threads_per_process: 1
        thread_type: CUDA
    num_jobs: 10
    run_config:
        result_dir: set_by_deepdrivemd
        dir_prefix: set_by_deepdrivemd
        pdb_file: set_by_deepdrivemd
        local_run_dir: /mnt/bb/$USER
        initial_pdb_dir: /path/to/initial_pdbs_and_tops
        solvent_type: explicit
        simulation_length_ns: 10.0
        report_interval_ps: 50.0
        wrap: false
        dt_ps: 0.002
        temperature_kelvin: 310.0
        reference_pdb_file: /path/to/reference.pdb
aggregation_stage:
    pre_exec:
    - . /sw/summit/python/3.6/anaconda3/5.3.0/etc/profile.d/conda.sh
    - conda activate /gpfs/alpine/proj-shared/med110/conda/pytorch
    - export LANG=en_US.utf-8
    - export LC_ALL=en_US.utf-8
    executable:
    - /gpfs/alpine/proj-shared/med110/conda/pytorch/bin/python
    arguments:
    - /path/to/data/aggregation/script/aggregate.py
    cpu_reqs:
        processes: 1
        process_type: 'null'
        threads_per_process: 26
        thread_type: OpenMP
    run_config:
        experiment_directory: set_by_deepdrivemd
        last_n_h5_files: null
        output_path: set_by_deepdrivemd
        rmsd: true
        fnc: false
        contact_map: false
        point_cloud: true
        verbose: true
ml_stage:
    pre_exec:
    - . /sw/summit/python/3.6/anaconda3/5.3.0/etc/profile.d/conda.sh
    - conda activate /gpfs/alpine/proj-shared/med110/conda/pytorch
    - module load gcc/7.4.0
    - module load cuda/10.1.243
    - module load hdf5/1.10.4
    - export LANG=en_US.utf-8
    - export LC_ALL=en_US.utf-8
    - export LD_LIBRARY_PATH=/gpfs/alpine/proj-shared/med110/atrifan/scripts/cuda/targets/ppc64le-linux/lib/:$LD_LIBRARY_PATH
    - unset CUDA_VISIBLE_DEVICES
    - export OMP_NUM_THREADS=4
    executable:
    - cat /dev/null; jsrun -n 1 -r 1 -g 6 -a 6 -c 42 -d packed /path/to/deepdrivemd/models/aae/bin/summit.sh
    arguments: []
    cpu_reqs:
        processes: 1
        process_type: MPI
        threads_per_process: 4
        thread_type: OpenMP
    gpu_reqs:
        processes: 1
        process_type: 'null'
        threads_per_process: 1
        thread_type: CUDA
    retrain_freq: 1
    run_config:
        input_path: set_by_deepdrivemd
        output_path: set_by_deepdrivemd
        init_weights_path: null
        dataset_name: point_cloud
        rmsd_name: rmsd
        fnc_name: fnc
        model_id: model_name
        num_points: 3375
        num_features: 0
        epochs: 10
        batch_size: 32
        optimizer:
            name: Adam
            lr: 0.0001
        latent_dim: 64
        encoder_filters:
        - 64
        - 128
        - 256
        - 256
        - 512
        encoder_kernel_sizes:
        - 5
        - 5
        - 3
        - 1
        - 1
        generator_filters:
        - 64
        - 128
        - 512
        - 1024
        discriminator_filters:
        - 512
        - 512
        - 128
        - 64
        encoder_relu_slope: 0.0
        generator_relu_slope: 0.0
        discriminator_relu_slope: 0.0
        use_encoder_bias: true
        use_generator_bias: true
        use_discriminator_bias: true
        noise_mu: 0.0
        noise_std: 1.0
        lambda_rec: 0.5
        lambda_gp: 10.0
        embed_interval: 1
        tsne_interval: 5
        sample_interval: 20
        num_data_workers: 0
        dataset_location: storage
        wandb_project_name: null
agent_stage:
    pre_exec:
    - . /sw/summit/python/3.6/anaconda3/5.3.0/etc/profile.d/conda.sh || true
    - conda activate /gpfs/alpine/proj-shared/med110/conda/pytorch
    - export LANG=en_US.utf-8
    - export LC_ALL=en_US.utf-8
    - unset CUDA_VISIBLE_DEVICES
    - export OMP_NUM_THREADS=4
    executable:
    - cat /dev/null; jsrun -n 1 -a 6 -g 6 -r 1 -c 7 /path/to/deepdrivemd/outlier_detection/optics.sh
    arguments: []
    cpu_reqs:
        processes: 1
        process_type: 'null'
        threads_per_process: 12
        thread_type: OpenMP
    gpu_reqs:
        processes: 1
        process_type: 'null'
        threads_per_process: 1
        thread_type: CUDA
    run_config:
        input_path: set_by_deepdrivemd
        output_path: set_by_deepdrivemd
        weights_path: set_by_deepdrivemd
        restart_points_path: set_by_deepdrivemd
        experiment_directory: set_by_deepdrivemd
        last_n_h5_files: null
        num_outliers: 11
        num_points: 304
        inference_batch_size: 128
