nohup bin/run.sh lassen-keras-dbscan_stream_10/1 > run_1.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_10/2 > run_2.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_10/3 > run_3.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_10/4 > run_4.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_10/5 > run_5.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_10/6 > run_6.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_10/7 > run_7.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_10/8 > run_8.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_10/9 > run_9.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_10/10 > run_10.log 2>&1 &
