nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/1 > run_1g.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/2 > run_2g.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/3 > run_3g.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/4 > run_4g.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/5 > run_5g.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/6 > run_6g.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/7 > run_7g.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/8 > run_8g.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/9 > run_9g.log 2>&1 &
nohup bin/run.sh lassen-keras-dbscan_stream_greedy_10/10 > run_10g.log 2>&1 &
