title: BBA ensemble
resource: llnl.lassen
queue: pdebug
schema_: local
project: cv19-a01
walltime_min: 30
cpus_per_node: 40
gpus_per_node: 4
hardware_threads_per_cpu: 4

output_directory: /p/gpfs1/brace3/runs/ensemble-run-1
input_pdb_file: /p/gpfs1/brace3/data/file_name.pdb
num_tasks: 120

task_config:
    pre_exec:
    - . /etc/profile.d/conda.sh
    - module load cuda/9.1.85
    - unset PYTHONPATH
    - conda activate /p/gpfs1/brace3/envs/conda-openmm
    executable: /p/gpfs1/brace3/envs/conda-openmm/bin/python
    arguments:
    - /p/gpfs1/brace3/src/DeepDriveMD-pipeline/examples/ensemble-md/md.py
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 4
        thread_type: OpenMP
    gpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: CUDA

sim_params:
    solvent_type: implicit
    simulation_length_ns: 1.0
    report_interval_ps: 1.0
    dt_ps: 0.002
    temperature_kelvin: 310.0
    heat_bath_friction_coef: 1.0
