project:
	PYTHONPATH=/usr/workspace/cv_ddmd/yakushin/Integration1/DeepDriveMD-pipeline/deepdrivemd/misc:${PYTHONPATH} python dbscan.py -c ../../../../Outputs/${d}/agent_runs/stage0000/task0000/stage0000_task0000.yaml -p
run:
	PYTHONPATH=/usr/workspace/cv_ddmd/yakushin/Integration1/DeepDriveMD-pipeline/deepdrivemd/misc:${PYTHONPATH} python dbscan.py -c ../../../../Outputs/${d}/agent_runs/stage0000/task0000/stage0000_task0000.yaml
clean:
	rm -rf *~ __pycache__ 
